/**
 * Generated by `npm run sprites` — do not edit.
 *
 * The layout of `assets/character/cat-sheet.png`: which row holds which clip,
 * how many frames it uses, and how fast it plays. Edit the clip table in
 * `scripts/sprites/clips.mjs` and regenerate instead.
 */

export interface SpriteClip {
  name: string;
  /** Row index in the sheet. */
  row: number;
  /** Frames used in that row, counted from column 0. */
  frames: number;
  fps: number;
  /** One-shot clips stop on their last frame; the default is to loop. */
  loop?: boolean;
}

/** Edge of one frame in sheet pixels; frames are square. */
export const FRAME_SIZE = 192;

/** Columns in the sheet; short clips leave the remainder of their row empty. */
export const SHEET_COLUMNS = 12;

export const SPRITE_CLIPS: readonly SpriteClip[] = [
  { name: 'idle', row: 0, frames: 12, fps: 10 },
  { name: 'idleBlink', row: 1, frames: 12, fps: 10 },
  { name: 'thinking', row: 2, frames: 12, fps: 9 },
  { name: 'reading', row: 3, frames: 12, fps: 10 },
  { name: 'typing', row: 4, frames: 8, fps: 14 },
  { name: 'executing', row: 5, frames: 10, fps: 12 },
  { name: 'working', row: 6, frames: 12, fps: 8 },
  { name: 'success', row: 7, frames: 10, fps: 12 },
  { name: 'error', row: 8, frames: 8, fps: 14 },
  { name: 'sleeping', row: 9, frames: 12, fps: 6 },
  { name: 'poke', row: 10, frames: 8, fps: 16, loop: false },
];

export const clipByName = (name: string): SpriteClip | undefined =>
  SPRITE_CLIPS.find((clip) => clip.name === name);
