// Bakes the character sheet: every clip in `sprites/clips.mjs`, one row per
// clip, drawn by `sprites/cat.mjs`.
//
// Two outputs, written together so they can never disagree:
//   assets/character/cat-sheet.png          the artwork
//   src/renderer/rig2d/sheetManifest.ts     the row/frame/timing table
//
// The manifest is a TypeScript module rather than JSON on purpose: the renderer
// runs under `default-src 'none'` with no `connect-src`, so it cannot fetch a
// sidecar file. Bundling the table in means the only thing loaded at runtime is
// the image itself, which `img-src 'self'` already allows.
//
// Run via `npm run sprites`.

import fs from 'node:fs/promises';
import path from 'node:path';
import { root } from './bundles.mjs';
import { CLIPS } from './sprites/clips.mjs';
import { drawCat } from './sprites/cat.mjs';
import { Bitmap, encodePng } from './sprites/raster.mjs';

/**
 * Frame edge in pixels. The character occupies roughly 200 logical pixels in
 * the overlay, so 192 is about 1:1 at 100% and softens gracefully at 200%.
 * Doubling this quadruples the sheet for detail nobody sees at overlay size.
 */
const FRAME = 192;

const SHEET_PATH = path.join(root, 'assets/character/cat-sheet.png');
const MANIFEST_PATH = path.join(root, 'src/renderer/rig2d/sheetManifest.ts');

const columns = Math.max(...CLIPS.map((c) => c.frames));
const sheet = new Bitmap(columns * FRAME, CLIPS.length * FRAME);

CLIPS.forEach((clip, row) => {
  for (let i = 0; i < clip.frames; i += 1) {
    // A looping clip samples [0, 1) so the last frame flows into the first; a
    // one-shot samples [0, 1] so it actually reaches its end pose.
    const t = clip.loop === false ? i / (clip.frames - 1) : i / clip.frames;
    drawCat(FRAME, clip.pose(t)).blitInto(sheet, i * FRAME, row * FRAME);
  }
  process.stdout.write(`  ${clip.name} (${clip.frames} frames)\n`);
});

await fs.mkdir(path.dirname(SHEET_PATH), { recursive: true });
const png = encodePng(sheet);
await fs.writeFile(SHEET_PATH, png);

const rows = CLIPS.map(
  (clip, row) =>
    `  { name: '${clip.name}', row: ${row}, frames: ${clip.frames}, fps: ${clip.fps}` +
    `${clip.loop === false ? ', loop: false' : ''} },`,
).join('\n');

await fs.mkdir(path.dirname(MANIFEST_PATH), { recursive: true });
await fs.writeFile(
  MANIFEST_PATH,
  `/**
 * Generated by \`npm run sprites\` — do not edit.
 *
 * The layout of \`assets/character/cat-sheet.png\`: which row holds which clip,
 * how many frames it uses, and how fast it plays. Edit the clip table in
 * \`scripts/sprites/clips.mjs\` and regenerate instead.
 */

export interface SpriteClip {
  name: string;
  /** Row index in the sheet. */
  row: number;
  /** Frames used in that row, counted from column 0. */
  frames: number;
  fps: number;
  /** One-shot clips stop on their last frame; the default is to loop. */
  loop?: boolean;
}

/** Edge of one frame in sheet pixels; frames are square. */
export const FRAME_SIZE = ${FRAME};

/** Columns in the sheet; short clips leave the remainder of their row empty. */
export const SHEET_COLUMNS = ${columns};

export const SPRITE_CLIPS: readonly SpriteClip[] = [
${rows}
];

export const clipByName = (name: string): SpriteClip | undefined =>
  SPRITE_CLIPS.find((clip) => clip.name === name);
`,
);

const kb = (n) => `${Math.round(n / 102.4) / 10} kB`;
console.log(
  `saber: sprite sheet written — ${sheet.width}x${sheet.height}, ${kb(png.length)} ` +
    `(${path.relative(root, SHEET_PATH)})`,
);
